;=======================================;
;	Music_No. EQU ;
;=======================================;
;	extern	musstop		;0
;	extern	mustitle1
;	extern	mustitle2
;	extern	mustitle3
;	extern	musstart
;	extern	musasa
;	extern	musrinia
;	extern	musfield15
;	extern	musgoroad
;	extern	musfield18
;	extern	musroadleague
;	extern	musroad38_39
;	extern	musroad42_44
;	extern	musfield13
;	extern	mustsur1
;	extern	mustsur2
;	extern	muskoukan11
;	extern	muspmc
;	extern	musundung
;	extern	muswakaba
;	extern	muskogane
;	extern	muskuchi
;	extern	musfight11
;	extern	musfight12
;	extern	musfight13
;	extern	musfight14
;	extern	musdealer1
;	extern	musdealer2
;	extern	musdealer3
;	extern	musdealerboy
;	extern	musdealergirl
;	extern	musdealerrocket
;	extern	musraibaru
;	extern	musraibaru2
;	extern	muslabo11
;	extern	musvictory1
;	extern	musvictory2
;	extern	musvictory22
;	extern	musvictory3
;	extern	musvictory4
;	extern	musgym
;	extern	muscasino
;	extern	muschari
;	extern	musdendou
;	extern	musshinka
;	extern	musending
;	extern	musendafter
;	extern	muskiniko
;	extern	musflower
;	extern	mushoshi
;	extern	mustown1
;	extern	mustown3
;	extern	musdigda
;	extern	mussenkyu
;	extern	musgotown1
;	extern	mustown12
;	extern	mustown14
;	extern	mussea
;	extern	musnami
;	extern	musshiai
;	extern	musazitotyouji
;	extern	musradio
;	extern	musfuemusic
;	extern	muskomori
;	extern	musmarch
