	extern	mushariusagi		;MVC01
	extern	mushariusagi@		;MVC02
	extern	musyaddon		;MVC03
	extern	musgarura		;MVC04
	extern	muscyhorne		;MVC05
	extern	musbettobeter		;MVC06
	extern	musbiriridama		;MVC07
	extern	musgengar		;MVC08
	extern	musfushigiso		;MVC09
	extern	musmycor		;MVC10
	extern	musmycor@		;MVC11
	extern	mustamatama		;MVC12
	extern	musbeloringa		;MVC13
	extern	musnasshii		;MVC14
	extern	muspip			;MVC15
	extern	musgyace		;MVC16
	extern	musomom			;MVC17
	extern	musgagarth		;MVC18
	extern	musmonjara		;MVC19
	extern	musomega		;MVC20
	extern	muscaiross		;MVC21
	extern	muswing			;MVC22
	extern	musstrike		;MVC23
	extern	musgyaradoss		;MVC24
	extern	musshellder		;MVC25
	extern	muskarakara		;MVC26
	extern	musambler		;MVC27
	extern	musrapruth		;MVC28
	extern	musgouth		;MVC29
	extern	muskarabatheo		;MVC30
	extern	musmimi			;MVC31
	extern	musyaddohogera		;MVC32
	extern	mus34			;MVC34
	extern	mus36			;MVC35
	extern	musdog			;MVC36
	extern	muskingthaurus		;MVC37
	extern	mussutegon		;MVC38
	extern	museleking		;MVC39



	extern	muskarasu		;MVC51
	extern	muskawaii4		;MVC52
	extern	muskawaii1		;MVC53
	extern	musneko			;MVC54
	extern	muskaijyuu2		;MVC55
	extern	musmee1			;MVC56
	extern	muskawaii2		;MVC57
	extern	mushoho			;MVC58
	extern	muspaon			;MVC59
	extern	musyadoking		;MVC60
	extern	musgururu		;MVC61
	extern	muschiko		;MVC62
	extern	muskaijyu60		;MVC63
	extern	musmoo			;MVC64
	extern	muswataneko		:MVC65
	extern	muskapoera		;MVC66
	extern	muslediba		;MVC67
	extern	mustora			;MVC68
	extern	musnyura		;MVC69
	extern	mushaneei		;MVC70
	extern	muskaijyu10		;MVC71
	extern	muskaijyu20		;MVC72
	extern	muskaijyu30		;MVC73
	extern	muskaijyu40		;MVC74
	extern	muskaijyu50		;MVC75
	extern	mussui			;MVC76
	extern	musnezumi		;MVC77
	extern	mushouou		;MVC78
	extern	musgulanbull		;MVC79
	extern	musdonfan		;MVC80

	extern	musearthtron		;MVC81
	extern	musyossy		;MVC82
	extern	musyoyossy		;MVC83



	extern	m_wngo			;00
	extern	m_kusuri		;01
	extern	m_itemuse		;02
	extern	m_syu			;03
	extern	m_rinrin		;04
	extern	m_pi			;05
	extern	m_warai			;06
	extern	m_taberu		;07
	extern	m_computer		;08
	extern	m_poweroff		;09
	extern	m_networks		;10
	extern	m_syowan		;11
	extern	m_switch		;12
	extern	m_poko			;13
	extern	m_warpup		;14
	extern	m_warpdown		;15
	extern	m_turnup		;16
	extern	m_jump			;17
	extern	m_sucha			;18
	extern	m_bird			;19
	extern	m_boboo			;20
	extern	m_pyun			;21
	extern	m_iwa			;22
	extern	m_ship			;23
	extern	m_get			;24
	extern	m_go			;25
	extern	m_door			;26
	extern	m_kon			;27
	extern	m_cha			;28
	extern	m_chikin		;29
	extern	m_boo			;30
	extern	m_zazaza		;31
	extern	m_save			;32
	extern	m_fue			;33
	extern	m_pinpon		;34
	extern	m_piew			;35
	extern	m_powan			;36
	extern	m_bashi			;37
	extern	m_nigeru		;38
	extern	m_zukan			;39
	extern	m_nidojump		;40
	extern	m_nidopyon1		;41
	extern	m_nidopyon2		;42
	extern	m_gengerhand		;43
	extern	m_gengerpunch		;44
	extern	m_logoin		;45
	extern	m_slotstop		;46
	extern	m_payout		;47
	extern	m_coin			;48
	extern	m_star			;49
	extern	m_sasaru		;50
	extern	m_ochiru		;51
	extern	m_agaru			;52
	extern	m_hataku		;53
	extern	m_punch			;54
	extern	m_punch2		;55
	extern	m_punch3		;56
	extern	m_hikkaki		;57
	extern	m_hasami		;58
	extern	m_kama			;59
	extern	m_kiru			;60
	extern	m_tsubasa		;61
	extern	m_fukitobashi		;62
	extern	m_shime			;63
	extern	m_muchi2		;64
	extern	m_kick			;65
	extern	m_kick2			;66
	extern	m_zutsuki		;67
	extern	m_tsuno			;68
	extern	m_taiatari		;69
	extern	m_hari			;70
	extern	m_kona			;71
	extern	m_binta			;72
	extern	m_kamitsuki		;73
	extern	m_tobigeri		;74
	extern	m_fumitsuke		;75
	extern	m_sippo			;76
	extern	m_choppu		;77
	extern	m_seoinage		;78
	extern	m_suitori		;79
	extern	m_kiai			;80
	extern	m_kaminari		;81
	extern	m_onpa			;82
	extern	m_beam			;83
	extern	m_fire			;84
	extern	m_water			;85
	extern	m_screw			;86
	extern	m_kouzui		;87
	extern	m_saike			;88
	extern	m_soura			;89
	extern	m_denki			;90
	extern	m_psycho		;91
	extern	m_iya			;92
	extern	m_hone			;93
	extern	m_toumei		;94
	extern	m_jibaku		;95
	extern	m_utau			;96
	extern	m_beam2			;97
	extern	m_syakin		;98
	extern	m_fanfare1		;99
	extern	m_fanfare2		;100
	extern	m_fanfare3		;101
	extern	m_fanfare4		;102
	extern	m_fanfare5		;103
	extern	m_fanfare6		;104
	extern	m_fanfare7		;105
	extern	m_fanfare8		;106
	extern	m_fanfare9		;107
	extern	m_fanfare10		;107
	extern	m_fanfare11		;107
	extern	m_fanfare12		;107
	extern	m_fanfare13		;107
	extern	m_fanfare14		;107
	extern	m_fanfare15		;107
	extern	m_fanfare16		;107
	extern	m_fanfare17		;107
	extern	m_fanfare18		;107
	extern	m_fanfare19		;107
	extern	m_fanfare20		;107
	extern	m_psycho2
	extern	m_telephone
	extern	m_telstop1
	extern	m_telstop2
	extern	m_gasagasa
	extern	m_elev

	extern	m_waza02
	extern	m_waza03
	extern	m_waza04
	extern	m_waza05
	extern	m_waza06
	extern	m_waza07
	extern	m_waza08
	extern	m_waza09
	extern	m_waza0a
	extern	m_waza0b
	extern	m_waza0c
	extern	m_waza0d
	extern	m_waza0e
	extern	m_waza0f
	extern	m_waza10
	extern	m_waza11
	extern	m_waza12
	extern	m_waza13
	extern	m_waza14
	extern	m_waza15
	extern	m_waza16
	extern	m_waza17
	extern	m_waza18
	extern	m_waza19
	extern	m_waza1a
	extern	m_waza1b
	extern	m_waza1c
	extern	m_waza1d
	extern	m_waza1e
	extern	m_waza1f
	extern	m_waza20
	extern	m_waza21
	extern	m_waza22
	extern	m_waza23
	extern	m_waza24
	extern	m_waza25
	extern	m_waza27

	extern	m_se28
	extern	m_se29
	extern	m_se30
	extern	m_se31
	extern	m_fan101
	extern	m_fan105
	extern	m_fan106
	extern	m_fan107
	extern	m_fan108
	extern	m_se32
	extern	m_se33
	extern	m_se34
	extern	m_se35

	extern	m_se37
	extern	m_se38
	extern	m_se39
	extern	m_se3a
	extern	m_wngo2
	extern	m_waza26
	extern	m_waza3b
	extern	m_se3c
	extern	m_se3d
	extern	m_se3e
	extern	m_se3f
	extern	m_slot1
	extern	m_se40

	extern	m_mailpin
	extern	m_mailpin2
	extern	m_opsuikun01
	extern	m_opsuikun02
	extern	m_opsuikun03
	extern	m_opsuikun04
	extern	m_opsuikun05
	extern	m_opsuikun06
	extern	m_opsuikun07
	extern	m_opsuikun08
	extern	m_opsuikun09
	extern	m_opsuikun0a
	extern	m_opsuikun0b
	extern	m_opsuikun0c
	extern	m_kururin
	extern	m_logoin2
	extern	m_ptpwarn
	extern	m_ptpfend
	extern	m_folopen

	extern	m_bluestar
	extern	m_bluesing
	extern	m_fue3

	extern	m_bidbid
	extern	m_wriggle
	extern	m_wah
	extern	m_won
	extern	m_bua
	extern	m_tamabig
	extern	m_tama1
	extern	m_tama2
	extern	m_tama3
	extern	m_tama4
	extern	m_tama5
	extern	m_tama6
	extern	m_tama7
	extern	m_batontatti
	extern	m_waiki
	extern	m_kaasaa
	extern	m_bekesmall
	extern	m_bekebig
	extern	m_tamago
	extern	m_kyushi
